### PR TITLE
Setup Travis for template testing

### PR DESCRIPTION
**Pull request by laughedelic**
It should be able to create a project from the template and compile it. Relevant documentation:
- http://www.foundweekends.org/giter8/testing.html

### CODE REVIEW

**Comment by laughedelic** [comment]
This is ready, but I don't have any administration permissions in the era7bio org, so I can't turn on Travis CI for this repo. 
@eparejatobes please, turn the switch on for this repo at https://travis-ci.org/profile/era7bio

**Comment by laughedelic** [comment]
@eparejatobes ok. Anyway, I can't transfer it, because I don't have admin rights for it.

**Comment by eparejatobes** [comment]
> @eparejatobes ok. Anyway, I can't transfer it, because I don't have admin rights for it.

It can't be transfer at all right now, as some statika template in the ohnosequences org is a fork of this repo; "unfork" that one first if you want me to transfer this.

**Comment by laughedelic** [comment]
Done 👌

**Comment by laughedelic** [comment]
I just noticed that the repo is transferred. I still don't have access to its settings on Travis, but CI seems to be turned on. Mering.

**Comment by laughedelic** [comment]
@eparejatobes your review is blocking this

**Pull request merged**
